source ~/.zsh/oh-my-zsh-config.zsh
source ~/.oh-my-zsh/oh-my-zsh.sh
source ~/.zsh/aliases.zsh

# macOS
if [[ `uname` == "Darwin" ]]; then
    source ~/.zsh/macos.zsh
fi

export PATH="$HOME/dotfiles/scripts:$PATH"